/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VisorE.java
 *
 * Created on Mar 9, 2010, 10:24:48 PM
 */

package VisorEstadistico;

/**
 *
 * @author Carlos F
 */
public class VisorE extends javax.swing.JFrame {

    /** Creates new form VisorE */
    public VisorE() {
        super("Visor Estádistico");
        initComponents();
        setLocation(350, 650);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xMedia = new javax.swing.JLabel();
        xDesviacionStd = new javax.swing.JLabel();
        xModa = new javax.swing.JLabel();
        xPromedio = new javax.swing.JLabel();
        xMaximo = new javax.swing.JLabel();
        xMinimo = new javax.swing.JLabel();
        xMediaLabel = new javax.swing.JLabel();
        xDesviacionEstLabel = new javax.swing.JLabel();
        xModaLabel = new javax.swing.JLabel();
        xPromedioLabel = new javax.swing.JLabel();
        xMaximoLabel = new javax.swing.JLabel();
        xMinimoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setName("vframe0"); // NOI18N
        setResizable(false);

        xMedia.setBackground(new java.awt.Color(0, 0, 0));
        xMedia.setFont(new java.awt.Font("Tahoma", 0, 48));
        xMedia.setForeground(new java.awt.Color(0, 255, 0));
        xMedia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xMedia.setText("0");
        xMedia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xMedia.setOpaque(true);

        xDesviacionStd.setBackground(new java.awt.Color(0, 0, 0));
        xDesviacionStd.setFont(new java.awt.Font("Tahoma", 0, 48));
        xDesviacionStd.setForeground(new java.awt.Color(0, 255, 0));
        xDesviacionStd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xDesviacionStd.setText("0");
        xDesviacionStd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xDesviacionStd.setOpaque(true);

        xModa.setBackground(new java.awt.Color(0, 0, 0));
        xModa.setFont(new java.awt.Font("Tahoma", 0, 48));
        xModa.setForeground(new java.awt.Color(0, 255, 0));
        xModa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xModa.setText("0");
        xModa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xModa.setOpaque(true);

        xPromedio.setBackground(new java.awt.Color(0, 0, 0));
        xPromedio.setFont(new java.awt.Font("Tahoma", 0, 48));
        xPromedio.setForeground(new java.awt.Color(0, 255, 0));
        xPromedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xPromedio.setText("0");
        xPromedio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xPromedio.setOpaque(true);

        xMaximo.setBackground(new java.awt.Color(0, 0, 0));
        xMaximo.setFont(new java.awt.Font("Tahoma", 0, 48));
        xMaximo.setForeground(new java.awt.Color(0, 255, 0));
        xMaximo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xMaximo.setText("0");
        xMaximo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xMaximo.setOpaque(true);

        xMinimo.setBackground(new java.awt.Color(0, 0, 0));
        xMinimo.setFont(new java.awt.Font("Tahoma", 0, 48));
        xMinimo.setForeground(new java.awt.Color(0, 255, 0));
        xMinimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xMinimo.setText("0");
        xMinimo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xMinimo.setOpaque(true);

        xMediaLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        xMediaLabel.setText("Media");

        xDesviacionEstLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        xDesviacionEstLabel.setText("Desviación Estandard");

        xModaLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        xModaLabel.setText("Moda");

        xPromedioLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        xPromedioLabel.setText("Promedio");

        xMaximoLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        xMaximoLabel.setText("Máximo");

        xMinimoLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        xMinimoLabel.setText("Mínimo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Periodo mostrado:");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(xMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(xMediaLabel)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(xDesviacionEstLabel)
                    .addComponent(xDesviacionStd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(xModaLabel)
                    .addComponent(xModa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(xPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(xPromedioLabel)
                        .addGap(78, 78, 78)
                        .addComponent(xMaximoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(xMinimoLabel)
                        .addGap(62, 62, 62))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(612, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xMediaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(xMaximoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(xMinimoLabel))
                    .addComponent(xModaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xPromedioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xDesviacionEstLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xDesviacionStd)
                    .addComponent(xMedia)
                    .addComponent(xMinimo)
                    .addComponent(xMaximo)
                    .addComponent(xPromedio)
                    .addComponent(xModa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisorE().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel xDesviacionEstLabel;
    private javax.swing.JLabel xDesviacionStd;
    private javax.swing.JLabel xMaximo;
    private javax.swing.JLabel xMaximoLabel;
    private javax.swing.JLabel xMedia;
    private javax.swing.JLabel xMediaLabel;
    private javax.swing.JLabel xMinimo;
    private javax.swing.JLabel xMinimoLabel;
    private javax.swing.JLabel xModa;
    private javax.swing.JLabel xModaLabel;
    private javax.swing.JLabel xPromedio;
    private javax.swing.JLabel xPromedioLabel;
    // End of variables declaration//GEN-END:variables

}
